### ISSUE TITLE
Change Http Status code

### ISSUE THREAD

**Issue by balasubramanian-v** [14Praveen08/APIs#2]
https://github.com/14Praveen08/APIs/blob/2dce7ede003fb2f252ec3673858a3561d8b1d3a0/src/main/java/com/revature/organization/service/OrganizationServiceImpl.java#L63

http status code ok varakoodathu

**Comment by 14Praveen08** [comment]
Ok

**Comment by 14Praveen08** [comment]
Done da. Still have to push
